package com.learn.service.cxfsoap.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.learn.service.cxfsoap.UserServiceCXF;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T14:45:08.737+03:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "UserServiceCXFimplService", 
                  wsdlLocation = "http://localhost:8080/webapplication/cxfsoap/UserService?wsdl",
                  targetNamespace = "http://impl.cxfsoap.service.learn.com/")
public class UserServiceCXFimplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.cxfsoap.service.learn.com/", "UserServiceCXFimplService");
    public final static QName UserServiceCXFimplPort = new QName("http://impl.cxfsoap.service.learn.com/", "UserServiceCXFimplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webapplication/cxfsoap/UserService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserServiceCXFimplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webapplication/cxfsoap/UserService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserServiceCXFimplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserServiceCXFimplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceCXFimplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserServiceCXFimplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserServiceCXFimplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserServiceCXFimplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserServiceCXF
     */
    @WebEndpoint(name = "UserServiceCXFimplPort")
    public UserServiceCXF getUserServiceCXFimplPort() {
        return super.getPort(UserServiceCXFimplPort, UserServiceCXF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceCXF
     */
    @WebEndpoint(name = "UserServiceCXFimplPort")
    public UserServiceCXF getUserServiceCXFimplPort(WebServiceFeature... features) {
        return super.getPort(UserServiceCXFimplPort, UserServiceCXF.class, features);
    }

}
