//v102 (c) 2008-2014 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
if(typeof Tynt.TCL=="undefined"){(function(){var fa=function(i,h){function J(a){var b=J.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},e=14;e--;)c[b.key[e]]=a[e]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(g,f,d){if(f)c[b.q.name][f]=d});return c}J.options={strictMode:false,key:["source","protocol","authority","userInfo","user","password","host","port","relative","path","directory","file","query","anchor"],q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};var q=h.body,p=h.documentElement,W=i.eval("/*@cc_on!@*/false"),K=function(a,b){for(var c="",e=0;e<b;e++)c+=a;return c},t=K("a",50),u=(Tynt.e||"")+"ic.tynt.com",X=(Tynt.e||"")+"de.tynt.com/deb/",L=u+"/b/s",D=function(a){return a.replace(/^\s+|\s+$/g,"")},E=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=
a[c]},M=function(a){for(var b={},c=a.length,e=[],g=0;g<c;g++)if(!b[a[g]]){b[a[g]]=true;e.push(a[g])}return e},N;N=i.addEventListener?function(a,b,c){a.addEventListener(b,c,false)}:function(a,b,c){a.attachEvent("on"+b,c)};var Y=function(a,b){var c=i.location.hostname.split("."),e,g=2;do{e=c.slice(c.length-g,c.length).join(".");e=a+";path=/;domain=."+e+";"+b;h.cookie=e;g++}while(h.cookie.indexOf(a)==-1&&g<=c.length);if(h.cookie.indexOf(a)==-1){e=a+";path=/;"+b;h.cookie=e}},O=function(a){h.readyState==
"complete"?a():N(i,"load",function(){setTimeout(function(){if(typeof h.readyState=="undefined"&&!W)h.readyState="complete";a()},10)})},n=function(a,b){var c=[],e=function(g,f){var d="http://"+g.replace("id="+t,"id="+M(Tynt).join("~"));if(d.indexOf(u+"/b/p?")>-1&&typeof Tynt.b=="string")d+="&b="+Tynt.b;var j=new Image(1,1);if(f)j.onerror=f;j.src=d};n=function(g,f){c.push([g,f])};O(function(){n=e;for(var g=0;g<c.length;g++)n(c[g][0],c[g][1]);c=null});n(a,b)},P=function(a){var b=[],c="",e;for(e in a)if(a.hasOwnProperty(e)){b.push(c,
e,"=",a[e]);c="&"}return b.join("")},R=function(a){for(var b=0,c=a.length<100?a.length:100,e=0;e<c;e++)b+=a.charCodeAt(e);a=Math.floor(Math.random()*3844);c=Math.abs((new Date).getTime()-12281184E5);return Q(c,7)+Q((b+a)%3844,2)},S=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?S(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},Q=function(a,b){var c=S(a);return K("0",b-c.length)+c},T=D((h.title||i.location.hostname).toString()).replace(RegExp(i.location.hash,"g"),""),Z=function(){for(var a=h.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")&&a[b].getAttribute("href")){a=a[b].getAttribute("href");b=i.location.protocol+"//"+i.location.host+i.location.pathname;var c=h.getElementsByTagName("base")[0];
if(c)if(c=c.getAttribute("href"))b=c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},v=function(a){return a.replace(/^https?:\/\//,"")},$=function(a,b){for(var c=b+"=",e=a.split(";"),g=0;g<e.length;g++){for(var f=e[g];f.charAt(0)==" ";)f=f.substring(1,f.length);if(f.indexOf(c)===0)return f.substring(c.length,f.length)}return null},aa=function(){var a=$(h.cookie,"tracertraffic"),
b=encodeURIComponent(v(Z())),c=i.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var e=u+"/b/p?id="+t+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+(new Date).getTime(),g=e+(b?"&cu="+b:""),f=g+(h.referrer?"&r="+encodeURIComponent(v(h.referrer)):"");a=f+"&t="+encodeURIComponent(T);n(a,function(){n(f,function(){n(g,function(){n(e)})})})},ba=function(){O(function(){var a={async:"async",src:"http://"+[X,"v2?id=",M(Tynt).join("~"),"&r=",encodeURIComponent(v(h.referrer))].join("")},b=h.createElement("script");
E(a,b);E(void 0,b.style);a=h.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)})},x=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},ca=x(),da=x(),ea=function(){var a,b=function(){i.removeEventListener("blur",b,false);F(a);return true};return function(c){a=c.target||c.srcElement;i.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){i.addEventListener("blur",b,
false);setTimeout(function(){h.removeEventListener("blur",b,false)},1E4)}return true}}(),U=function(a){F(a.target||a.srcElement,true)},z,V=function(a){a=a.target||a.srcElement;z=a.nodeName=="IMG"?a:null},G=function(){var a=function(d){return typeof d.pageX=="number"?{x:d.pageX-(p.scrollLeft?p.scrollLeft:q.scrollLeft),y:d.pageY-(p.scrollTop?p.scrollTop:q.scrollTop)}:{x:d.clientX,y:d.clientY}},b=function(d){d=a(d);return d.x<=0||d.y<=0||d.x>=q.clientWidth||d.y>=q.clientHeight},c=function(d){d=a(d);
return d.x<=0||d.y<=0||d.x>=p.clientWidth||d.y>=p.clientHeight},e=function(d){return d.target.nodeName=="#document"},g=function(d){d=a(d);return d.x<=4||d.y<=4||d.x>=p.clientWidth-4||d.y>=p.clientHeight-4},f=function(d){f=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?e:g;f(d)};return function(d){if(z&&f(d)){F(z);z=null}return true}}();Tynt.ci=function(){var a;return function(b,c){a=c||a;var e=L+["?ci=",b,"&id=",t,"&g=",a,
"&r=",encodeURIComponent(v(h.referrer)),"&ts=",(new Date).getTime()].join("");n(e)}}();Tynt.st=function(){var a;return function(b,c,e,g){a=e||a;b=[L,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",t,"&g=",a,"&r=",encodeURIComponent(v(h.referrer)),"&href=",encodeURIComponent(v(i.location.href)),"&ts=",(new Date).getTime()];c="";if(g){c=[];e="";for(var f in g)if(g.hasOwnProperty(f)){c.push(e,encodeURIComponent(f),"=",encodeURIComponent(g[f]));e="&"}c="&"+c.join("")}n(b.join("")+c)}}();if(typeof tyntLoadMethod!==
"undefined")if(Tynt.e||Math.random()<0.0010)Tynt.st("lm",tyntLoadMethod,t,{lmEx:tyntLoadException});if(Tynt.c)x=function(){};else{Tynt.c=true;Tynt.m=Tynt.m||[];Tynt.n=Tynt.n||[];x=function(){var a=true,b,c=function(e,g){var f;f=(f=D(g))?f.split(/\s+/i).length:0;var d={id:t,wc:f,c:g,f:a?1:0,t:T};E(e,d);a=false;f=d.trace_type;delete d.trace_type;var j=d.g;delete d.g;for(var k=[],l=["id","wc","f","w","h","t","c"],o=0;o<l.length;o++){var y=l[o],r=d[y];r&&k.push([y,encodeURIComponent(r).replace(/\'/g,
"%27")]);delete d[y]}for(var m in d)if(d.hasOwnProperty(m))(l=d[m])&&k.push([m,encodeURIComponent(l).replace(/\'/g,"%27")]);m=[];o=2048-(("http://"+u+"/a/t/x#?").length+(3+j.length)+5);y=k.length;var w=r=0,s=0,H,A,I,B,C=0;for(m[C]={g:j,tp:null};r<y&&m.length<35;){H=k[r][0];d=k[r][1];I=H.length+2;A=o-I-w;if(A>0){l=d.substring(s,s+A);B=l.slice(-2).indexOf("%");if(B>-1){l=d.substring(s,s+A-2+B);w+=B+2}w+=l.length+I;s+=l.length;m[C][H]=l}else w=o;if(w>=o){m[++C]={g:j,p:C};w=0}if(s>=d.length){r++;s=0}}m[0].tp=
m.length;n(u+"/b/t/"+f+"?"+P(m[0]));for(j=1;j<m.length;j++)n(u+"/b/x/"+f+"?"+P(m[j]))};if(i.addEventListener){navigator.userAgent.match(/Firefox\/2\b/)||q.addEventListener("copy",U,false);i.addEventListener("mousedown",V,false);i.addEventListener("dragleave",G,false);i.addEventListener("dragexit",G,false);h.addEventListener("contextmenu",ea,false)}else{q.attachEvent("oncopy",U);h.getElementsByTagName("html")[0].attachEvent("ondragleave",G);q.attachEvent("onmousedown",V)}if(h.cookie.indexOf("tracertraffic=")!==
-1)if(!h.referrer||h.referrer.indexOf(i.location.host)==-1)Y("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");aa();ba();return function(e,g){if(!h.getElementById("tyntSh")){var f,d,j;if(g)if(!h.selection||!h.selection.createRange){d=getSelection();j=d.rangeCount>0&&d.getRangeAt(0);f=d.toString()}else{d=h.selection.createRange();j=d.duplicate();f=d.text}var k=e.src;if(k&&!f&&da(k)){d={trace_type:3,g:R(k),w:e.width,h:e.height};for(j=0;j<Tynt.n.length;j++)Tynt.n[j](d,k);c(d,k)}else if(f&&D(f).length&&
e.nodeName!="TEXTAREA"&&e.nodeName!="INPUT"){k=ca(f);d={trace_type:1};if(k)b=R(f);d.g=b;for(var l=true,o=0;o<Tynt.m.length;o++)l=l&&Tynt.m[o](d,f,j,k);k&&l&&c(d,f)}}}}}if(!(/tracer=test|tracer=no_tracing|disableTracer=/.test(i.location.href)||/disableTracer=y/.test(h.cookie)))var F=x()};Tynt.TCL=function(i,h){h.body?fa(i,h):setTimeout(function(){Tynt.TCL(window,document)},300)}})();Tynt.TCL(window,document)};
